#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "kritr"
email = "equal.dog1561@krithikrao.com"

[ui]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
editor = ["nvim", "--cmd", "let g:flatten_wait=1"]

